language: python
python:
  - "2.7"
env: PYTHONPATH=$PWD:$PYTHONPATH PATH=$PWD/bin:$PATH
install:
  - pip install -r requirements.txt
script:
  - vs --help
  - find vsmomi -iname '*.py' | xargs python -m py_compile
  - python setup.py build
  - python setup.py bdist
  - python build-doc.py
